### 이미지는 0.5초 obj출력, 0.5초 흰배경 출력

In [61]:
import cv2 as cv

# 영상의 의미지를 연속적으로 캡쳐할 수 있게 하는 class
path = r'D:/Private/test.mp4'
outputPath = r'D:\Private\test_output_path'
vidcap = cv.VideoCapture(path)
count = 0

oldBGR = np.array([255,255,255])
bias = 0.1

while(vidcap.isOpened()):    
    ret, image = vidcap.read()
    #image shape = (480, 854, 3)
    row,col = image[0],image[1]
    newBGR = image[240,427,...]
    #RGB값 비교
    if(int(vidcap.get(cv.CAP_PROP_POS_FRAMES)) % 12 == 0):
        print(count , newBGR)
        #흰바탕1
        if newBGR[0] == 255 and newBGR[1] == 254 and newBGR[2] == 255:
            pass
        #흰바탕2
        elif newBGR[0] == 255 and newBGR[1] == 253 and newBGR[2] == 255:
            pass
        else:
            oldBGR = newBGR
            cv.imwrite(outputPath + r'/frame%d.jpg' % count, image)
            print(r'/frame%d.jpg Saved' % count)
            #print(count , newBGR)
            count +=1
vidcap.release()

0 [0 0 0]
/frame0.jpg Saved
1 [255 254 255]
1 [0 0 0]
/frame1.jpg Saved
2 [255 254 255]
2 [0 0 0]
/frame2.jpg Saved
3 [255 254 255]
3 [0 0 0]
/frame3.jpg Saved
4 [255 254 255]
4 [0 0 0]
/frame4.jpg Saved
5 [255 254 255]
5 [0 0 0]
/frame5.jpg Saved
6 [255 254 255]
6 [0 0 0]
/frame6.jpg Saved
7 [255 254 255]
7 [0 0 0]
/frame7.jpg Saved
8 [255 254 255]
8 [0 0 0]
/frame8.jpg Saved
9 [255 254 255]
9 [0 0 0]
/frame9.jpg Saved
10 [255 254 255]
10 [0 0 0]
/frame10.jpg Saved
11 [255 254 255]
11 [0 0 0]
/frame11.jpg Saved
12 [255 254 255]
12 [0 0 0]
/frame12.jpg Saved
13 [255 254 255]
13 [0 0 0]
/frame13.jpg Saved
14 [255 254 255]
14 [0 0 0]
/frame14.jpg Saved
15 [255 254 255]
15 [0 0 0]
/frame15.jpg Saved
16 [255 254 255]
16 [0 0 0]
/frame16.jpg Saved
17 [255 254 255]
17 [0 0 0]
/frame17.jpg Saved
18 [255 254 255]
18 [131 156 223]
/frame18.jpg Saved
19 [255 254 255]
19 [153 169 244]
/frame19.jpg Saved
20 [255 254 255]
20 [138 155 226]
/frame20.jpg Saved
21 [255 254 255]
21 [167 175 245]
/frame2

TypeError: 'NoneType' object is not subscriptable

In [43]:
newBGR[0]

255

In [35]:
brg = image[240,int(427/2),...]
brg

array([255, 255, 255], dtype=uint8)

In [36]:
image.shape

(480, 854, 3)

In [14]:
import numpy as np
oldBGR = np.array([255,255,255])
a= oldBGR * 0.8
a

array([204., 204., 204.])

In [32]:
newBGR = np.array([255,255,255])
oldBGR = np.array([250,250,250])
bias = 0.1
if (newBGR[0] <= (oldBGR - oldBGR * bias)[0] or newBGR[0] >= (oldBGR + oldBGR * bias)[0]) and(newBGR[1] <= (oldBGR - oldBGR * bias)[1] or newBGR[1] >= (oldBGR + oldBGR * bias)[1]) and(newBGR[2] <= (oldBGR - oldBGR * bias)[2] or newBGR[2] >= (oldBGR + oldBGR * bias)[2]):
    print('hi')
else :
    print('hello')

hello


In [28]:
oldBGR + oldBGR * bias

array([275., 275., 275.])

In [30]:
newBGR.all()

True