In [1]:
import sympy as sp
import numpy as np

In [4]:
#행렬의 임의 구분

mat = np.array([[1,2,3],[3,4,5],[1,0,2]])

In [6]:
spmat = sp.Matrix(mat)

In [7]:
spmat

Matrix([
[1, 2, 3],
[3, 4, 5],
[1, 0, 2]])

In [30]:
spmat.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]), (0, 1, 2))

In [31]:
spmat.rank()

3

In [14]:
# transpose (전치행렬) 구하기

a = np.transpose(mat)
a
# mat.T

array([[1, 3, 1],
       [2, 4, 0],
       [3, 5, 2]])

In [12]:
#역행렬 구하기

np.linalg.inv(mat)

array([[-1.33333333,  0.66666667,  0.33333333],
       [ 0.16666667,  0.16666667, -0.66666667],
       [ 0.66666667, -0.33333333,  0.33333333]])

In [13]:
#determinent 구하기

np.linalg.det(mat)

-6.000000000000001

In [16]:
# 내적

np.dot(mat,a)

array([[14, 26,  7],
       [26, 50, 13],
       [ 7, 13,  5]])

In [20]:
#eigenvalue, eigenvector 구하기

#eigenvalue
np.linalg.eigvals(mat)
#eigenvector
np.linalg.eig(mat)

array([ 6.        , -0.61803399,  1.61803399])

In [27]:
# svd
svd = np.linalg.svd(mat)
svd

(array([[-0.45204597,  0.01901765, -0.89179189],
        [-0.8615139 , -0.2684313 ,  0.43097382],
        [-0.23118875,  0.96311109,  0.13772726]]),
 array([8.1933548 , 1.23083598, 0.5949621 ]),
 array([[-0.39883253, -0.53093606, -0.74768945],
        [ 0.14367051, -0.8414524 ,  0.52088063],
        [ 0.9056994 , -0.10032321, -0.41187845]]))