# Tensor에 대한 기본적인 이해와 연산함수(01_1)

---

In [1]:
import torch as t

In [2]:
t.__version__

'1.3.1'

In [10]:
data =  t.FloatTensor([[1.,2.,3.,4.,5.,],[6.,7.,8.,9.,0.,]])

# check size(shape)
data.size()
    # data.shape
    
#slicing
data[:,1]

#indexing
data[1,1]

tensor(7.)

In [13]:
#broadcasting

data1 = t.Tensor([[1,2],[3,4]])
data2 = t.Tensor([[10,20],[30,40]])
data3 = t.Tensor([1,2])

print(data1+data2)
#element multipilcation
print(data1*data2)

#element multipilcation(broadcasting)
print(data1*data3)

#dot product
print(data1.matmul(data3))

tensor([[11., 22.],
        [33., 44.]])
tensor([[ 10.,  40.],
        [ 90., 160.]])
tensor([[1., 4.],
        [3., 8.]])


tensor([ 5., 11.])

In [31]:
#Mean Sum
data4 = t.FloatTensor([[1,2],[3,4]]) 
print(data4.mean())

#[1, 2]
#[3 ,4] 에 대해서 
#dim=0 으로 설정했을 경우 (1,3),(2,4)에 대한 평균을 (열 연산)
#dim=1 으로 설정했을 경우 (1,2),(3,4)에 대한 평균을 출력(행 연산)
print(data4.mean(dim=0))
print(data4.mean(dim=1))
#sum은 mean대신 sum

#Max & argmax
# .max()  = (max,argmax)
#argmax = max값의 index 리턴
print(data4.max())
print(data4.max(dim = 0)[0])
print(data4.max(dim = 0)[1])

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor(4.)
tensor([3., 4.])
tensor([1, 1])


# Tensor에 대한 기본적인 이해와 연산함수(01_2)

---

In [33]:
#view (reshape)
import numpy as np
data = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[8,9,0]]])
data_tp = t.FloatTensor(data)

In [34]:
data_tp.shape

torch.Size([2, 2, 3])

In [36]:
print(data_tp.view(-1,3))
print(data_tp.view(-1,3).shape)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.],
        [8., 9., 0.]])
torch.Size([4, 3])


In [37]:
print(data_tp.view(-1,1,3))
print(data_tp.view(-1,1,3).shape)

tensor([[[0., 1., 2.]],

        [[3., 4., 5.]],

        [[6., 7., 8.]],

        [[8., 9., 0.]]])
torch.Size([4, 1, 3])


In [38]:
data1 = t.FloatTensor([[0],[1],[2]])
print(data1)
print(data1.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [40]:
print(data1.squeeze())
print(data1.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [45]:
#type casting
data2= t.LongTensor([0,1,2])
data2.float()
data2.int()

tensor([0, 1, 2], dtype=torch.int32)

In [47]:
data3 = t.FloatTensor([[1,2],[3,4]]) 
data4 = t.FloatTensor([[1,2],[3,4]]) 

print(t.cat([data3,data4],dim = 0))
print(t.cat([data3,data4],dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [1., 2.],
        [3., 4.]])
tensor([[1., 2., 1., 2.],
        [3., 4., 3., 4.]])


In [50]:
print(t.stack([data3 ,data4,data3],dim = 0))
print(t.stack([data3 ,data4,data3],dim = 0).shape)
print(t.stack([data3 ,data4,data3],dim = 1))
print(t.stack([data3 ,data4,data3],dim = 1).shape)

tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]]])
torch.Size([3, 2, 2])
tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


In [55]:
#ones and zeros
data5 = t.Tensor([[0,1,2],[1,2,3]])

print(t.ones_like(data5))
print(t.zeros_like(data5))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [56]:
#in_place operation

x = t.Tensor([[1,2],[3,4]])

x.mul(2)
print(x)
x.mul_(2)
print(x)

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
